LEN_NAME_PROJECT = 200
OPEN_STATUS = 'open'
CLOSED_STATUS = 'closed'
CHOICES_STATUS = [(OPEN_STATUS, 'Открытый'), (CLOSED_STATUS, 'Закрытый')]
DEFAULT_PROJECT_STATUS = 'open'
MAX_LEN_STATUS_PROJECT = 6
PROJECT_STATUS_CLOSE = 'close'

LEN_NAME_SKILL = 124

PAGINATE_BY = 12

COUNT_SKILLS = 10

TEXT_COLOR = (255, 255, 255)
IMAGE_SIZE = 200
TEXT_SIZE = 0.6 * IMAGE_SIZE

LEN_NAME_USER = 124
LEN_SURNAME = 124
LEN_PHONE = 12
LEN_ABOUT = 256
